export const IDLE_FARM_ITEMS = {
  // material
  wood: 'wood',
  stick: 'stick',
  apple: 'apple',
  leaf: 'leaf',
  water: 'water',
  rock: 'rock',
  sand: 'sand',
  algae: 'algae',
  potato: 'potato',
  dirt: 'dirt',
  root: 'root',
  wheat: 'wheat',
  seed: 'seed',
  bug: 'bug',
  brokenBottle: 'broken bottle',
  goldNugget: 'gold nugget',
  cotton: 'cotton',
  coal: 'coal',
  ironOre: 'iron ore',
  copperOre: 'copper ore',
  dust: 'dust',
  aluminiumOre: 'aluminium ore',
  milk: 'milk',
  meat: 'meat',
  leather: 'leather',
  horn: 'horn',
  sawdust: 'sawdust',
  // refined
  plank: 'plank',
  thread: 'thread',
  ironIngot: 'iron ingot',
  copperIngot: 'copper ingot',
  aluminiumIngot: 'aluminium ingot',
  steelIngot: 'steel ingot',
  goldIngot: 'gold ingot',
  yoghurt: 'yoghurt',
  bacteria: 'bacteria',
  cheese: 'cheese',
  dustIngot: 'dust ingot',
  dirtIngot: 'dirt ingot',
  dusirtIngot: 'dusirt ingot',
  bread: 'bread',
  burntFood: 'burnt food',
  lava: 'lava',
  glass: 'glass',
  brokenGlass: 'broken glass',
  // product
  fabric: 'fabric',
  chair: 'chair',
  wire: 'wire',
  // box
  woodBox: 'wood box',
  stickBox: 'stick box',
  appleBox: 'apple box',
  leafBox: 'leaf box',
  waterBox: 'water box',
  rockBox: 'rock box',
  sandBox: 'sand box',
  algaeBox: 'algae box',
  potatoBox: 'potato box',
  dirtBox: 'dirt box',
  rootBox: 'root box',
  wheatBox: 'wheat box',
  seedBox: 'seed box',
  bugBox: 'bug box',
  brokenBottleBox: 'broken bottle box',
  goldNuggetBox: 'gold nugget box',
  cottonBox: 'cotton box',
  coalBox: 'coal box',
  ironOreBox: 'iron ore box',
  copperOreBox: 'copper ore box',
  dustBox: 'dust box',
  aluminiumOreBox: 'aluminium ore box',
  milkBox: 'milk box',
  meatBox: 'meat box',
  leatherBox: 'leather box',
  hornBox: 'horn box',
  sawdustBox: 'sawdust box',

  // consumables
  energyGlass: 'energy glass',
  energyDrink: 'energy drink',
  energyGalloon: 'energy galloon',
  timeSpeeder: 'time speeder',
  timeCompressor: 'time compressor',
  uselessDice: 'useless dice',
  commonDice: 'common dice',
  uncommonDice: 'uncommon dice',
  rareDice: 'rare dice',
  epicDice: 'epic dice',
  mythicDice: 'mythic dice',
  uselessLootbox: 'useless lootbox',
  commonLootbox: 'common lootbox',
  uncommonLootbox: 'uncommon lootbox',
  rareLootbox: 'rare lootbox',
  epicLootbox: 'epic lootbox',
  mythicLootbox: 'mythic lootbox',
} as const;
